apiVersion: v1
data:
  conf.toml: IkRiVXNlciIgPSAidGVjaENoYWxsYW5nZVVzZXIiCiJEYlBhc3N3b3JkIiA9ICJ0ZWN0Q2hhbGxlbmdlUGFzc3dvcmQiCiJEYk5hbWUiID0gInRlY2hEYiIKIkRiUG9ydCIgPSAiNTQzMiIKIkRiSG9zdCIgPSAicG9zdGdyZXNxbC1oYS1wZ3Bvb2wuZGIuc3ZjLmNsdXN0ZXIubG9jYWwiCiJEYlR5cGUiID0gInBvc3RncmVzIgoiTGlzdGVuSG9zdCIgPSAiMC4wLjAuMCIKIkxpc3RlblBvcnQiID0gIjMwMDAiCg==
kind: Secret
metadata:
  creationTimestamp: null
  name: appconfig