apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tech-challenge-app
      tier: app
  template:
    metadata:
      labels:
        app: tech-challenge-app
        tier: app
    spec:
      containers:
        - image: kazzcontainerregistry.azurecr.io/tech-challenge-app:latest
          imagePullPolicy: IfNotPresent
          name: tech-challenge-app
          ports:
            - containerPort: 80
              name: http
      imagePullSecrets: 
      - name: acs-secret

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tech-challenge-app
  name: tech-challenge-app
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: tech-challenge-app
  type: ClusterIP